import jsPDF from "jspdf";
import html2canvas from "html2canvas";

/**
 * Helper: Format currency with thousand separators
 */
const formatCurrency = (amount) => {
  return `$${parseFloat(amount || 0).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  })}`;
};

/**
 * Helper: Format number with thousand separators
 */
const formatNumber = (num) => {
  return parseFloat(num || 0).toLocaleString("en-US");
};

/**
 * Helper: Add page footer
 */
const addPageFooter = (doc, pageWidth, pageHeight, margin, pageNum, totalPages) => {
  const footerY = pageHeight - 10;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  
  // Left: Confidential notice
  doc.text("Confidential – Internal Use Only", margin, footerY);
  
  // Center: Report name
  doc.text("BananaMeow Admin Report", pageWidth / 2, footerY, { align: "center" });
  
  // Right: Page number
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, footerY, { align: "right" });
};

/**
 * Helper: Add professional header
 */
const addReportHeader = (doc, pageWidth, margin, title, metadata) => {
  let yPos = 10;
  
  // Logo area (left) - Text-based logo
  doc.setFontSize(16);
  doc.setTextColor(124, 58, 237);
  doc.setFont(undefined, "bold");
  doc.text("Banana Meow", margin, yPos);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("The Royal Cat Court", margin, yPos + 5);
  
  // Title (center)
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, "bold");
  const titleWidth = doc.getTextWidth(title);
  doc.text(title, (pageWidth - titleWidth) / 2, yPos);
  
  // Date/Time (right)
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.setFont(undefined, "normal");
  const dateTime = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit"
  });
  const dateTimeWidth = doc.getTextWidth(dateTime);
  doc.text(dateTime, pageWidth - margin, yPos, { align: "right" });
  
  yPos += 8;
  
  // Metadata row
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  const metadataText = [
    metadata.generatedBy && `Generated by: ${metadata.generatedBy}`,
    metadata.dateRange && `Period: ${metadata.dateRange}`,
    metadata.filters && `Filters: ${metadata.filters}`,
    metadata.sorting && `Sorting: ${metadata.sorting}`
  ].filter(Boolean).join(" • ");
  
  if (metadataText) {
    doc.text(metadataText, margin, yPos);
  }
  
  yPos += 5;
  
  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  
  return yPos + 8;
};

/**
 * Helper: Add executive summary boxes
 */
const addExecutiveSummary = (doc, pageWidth, pageHeight, margin, yPos, summaryData) => {
  const boxWidth = (pageWidth - 2 * margin - 10) / 2; // 2 columns with gap
  const boxHeight = 25;
  let currentX = margin;
  let currentY = yPos;
  let col = 0;
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, "bold");
  doc.text("Executive Summary", margin, currentY);
  currentY += 8;
  
  summaryData.forEach((item, index) => {
    // Check if we need a new page
    if (currentY + boxHeight > pageHeight - 30) {
      doc.addPage();
      const totalPages = doc.internal.pages.length - 1;
      addPageFooter(doc, pageWidth, pageHeight, margin, totalPages, totalPages);
      currentY = margin + 15;
      currentX = margin;
      col = 0;
    }
    
    // Draw box
    doc.setDrawColor(220, 220, 220);
    doc.setFillColor(250, 250, 250);
    doc.setLineWidth(0.5);
    doc.roundedRect(currentX, currentY, boxWidth, boxHeight, 2, 2, "FD");
    
    // Label
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.setFont(undefined, "normal");
    doc.text(item.label, currentX + 5, currentY + 6);
    
    // Value
    doc.setFontSize(14);
    doc.setTextColor(124, 58, 237);
    doc.setFont(undefined, "bold");
    doc.text(item.value, currentX + 5, currentY + 14);
    
    // Sub-value (if exists)
    if (item.subValue) {
      doc.setFontSize(7);
      doc.setTextColor(80, 80, 80);
      doc.setFont(undefined, "normal");
      doc.text(item.subValue, currentX + 5, currentY + 20);
    }
    
    // Move to next position
    col++;
    if (col >= 2) {
      col = 0;
      currentX = margin;
      currentY += boxHeight + 5;
    } else {
      currentX += boxWidth + 10;
    }
  });
  
  return currentY + (col > 0 ? boxHeight + 5 : 0) + 8;
};

/**
 * Helper: Add table with alternating rows
 */
const addTable = (doc, pageWidth, pageHeight, margin, yPos, headers, rows, options = {}) => {
  const colWidths = options.colWidths || headers.map(() => (pageWidth - 2 * margin) / headers.length);
  const headerHeight = 8;
  const rowHeight = 7;
  let currentY = yPos;
  
  // Table title
  if (options.title) {
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, "bold");
    doc.text(options.title, margin, currentY);
    currentY += 8;
  }
  
  // Draw header
  let currentX = margin;
  doc.setFillColor(124, 58, 237);
  doc.setDrawColor(124, 58, 237);
  doc.rect(currentX, currentY, pageWidth - 2 * margin, headerHeight, "F");
  
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont(undefined, "bold");
  
  headers.forEach((header, colIndex) => {
    const align = options.alignments?.[colIndex] || "left";
    const xPos = align === "right" 
      ? currentX + colWidths[colIndex] - 3
      : align === "center"
      ? currentX + colWidths[colIndex] / 2
      : currentX + (colIndex === 0 ? 3 : 0);
    doc.text(header, xPos, currentY + 6, {
      align: align === "right" ? "right" : align === "center" ? "center" : "left",
      maxWidth: colWidths[colIndex] - 6
    });
    currentX += colWidths[colIndex];
  });
  
  currentY += headerHeight;
  
    // Draw rows
    rows.forEach((row, rowIndex) => {
      const isTotalRow = row[0] === "TOTAL" || row[0] === "SUMMARY";
      
      // Check if we need a new page
      if (currentY + rowHeight > pageHeight - 25) {
        doc.addPage();
        const totalPages = doc.internal.pages.length - 1;
        addPageFooter(doc, pageWidth, pageHeight, margin, totalPages, totalPages);
        
        // Repeat header on new page
        currentY = margin + 5;
        currentX = margin;
        doc.setFillColor(124, 58, 237);
        doc.rect(currentX, currentY, pageWidth - 2 * margin, headerHeight, "F");
        
        doc.setFontSize(9);
        doc.setTextColor(255, 255, 255);
        doc.setFont(undefined, "bold");
        currentX = margin;
        headers.forEach((header, colIndex) => {
          const align = options.alignments?.[colIndex] || "left";
          const xPos = align === "right" 
            ? currentX + colWidths[colIndex] - 3
            : align === "center"
            ? currentX + colWidths[colIndex] / 2
            : currentX + (colIndex === 0 ? 3 : 0);
          doc.text(header, xPos, currentY + 6, {
            align: align === "right" ? "right" : align === "center" ? "center" : "left",
            maxWidth: colWidths[colIndex] - 6
          });
          currentX += colWidths[colIndex];
        });
        currentY += headerHeight;
      }
      
      // Style total/summary rows differently
      if (isTotalRow) {
        doc.setFillColor(240, 240, 240);
        doc.rect(margin, currentY, pageWidth - 2 * margin, rowHeight, "F");
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(margin, currentY, pageWidth - margin, currentY);
      } else if (rowIndex % 2 === 0) {
        // Alternating row color for regular rows
        doc.setFillColor(250, 250, 250);
        doc.rect(margin, currentY, pageWidth - 2 * margin, rowHeight, "F");
      }
      
      // Draw row content
      currentX = margin;
      doc.setFontSize(isTotalRow ? 9 : 8);
      doc.setTextColor(isTotalRow ? 0 : 0, 0, 0);
      doc.setFont(undefined, isTotalRow ? "bold" : "normal");
      
      row.forEach((cell, colIndex) => {
        const align = options.alignments?.[colIndex] || "left";
        const xPos = align === "right" 
          ? currentX + colWidths[colIndex] - 3
          : align === "center"
          ? currentX + colWidths[colIndex] / 2
          : currentX + 3;
        doc.text(String(cell), xPos, currentY + 5, {
          align: align === "right" ? "right" : align === "center" ? "center" : "left",
          maxWidth: colWidths[colIndex] - 6
        });
        currentX += colWidths[colIndex];
      });
      
      currentY += rowHeight;
    });
  
  return currentY + 5;
};

/**
 * Helper: Add section divider
 */
const addSectionDivider = (doc, pageWidth, margin, yPos, title) => {
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, "bold");
  doc.text(title, margin, yPos);
  yPos += 5;
  
  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  
  return yPos + 8;
};

/**
 * Helper: Generate analytics insights
 */
const generateInsights = (stats, analytics, period) => {
  const insights = [];
  const statsData = stats?.stats || stats || {};
  
  // Revenue insight
  if (statsData.totalRevenue > 0) {
    const revenueGrowth = statsData.revenueGrowth || "0%";
    if (parseFloat(revenueGrowth) > 0) {
      insights.push(`Revenue increased by ${revenueGrowth} compared to previous period.`);
    } else if (parseFloat(revenueGrowth) < 0) {
      insights.push(`Revenue decreased by ${Math.abs(parseFloat(revenueGrowth))}% compared to previous period.`);
    }
  }
  
  // Donations insight
  if (statsData.totalDonations > 0 && analytics?.donationByCat?.length > 0) {
    const topCat = analytics.donationByCat[0];
    if (topCat) {
      const percentage = ((topCat.totalAmount / statsData.totalDonations) * 100).toFixed(1);
      insights.push(`${topCat.catName} received ${percentage}% of total donations.`);
    }
  }
  
  // Top spender insight
  if (statsData.topSpenderAmount > 0 && statsData.totalRevenue > 0) {
    const percentage = ((statsData.topSpenderAmount / statsData.totalRevenue) * 100).toFixed(1);
    insights.push(`Top spender contributed ${percentage}% of total revenue.`);
  }
  
  // User growth insight
  if (statsData.newUsersThisWeek > 0) {
    insights.push(`${formatNumber(statsData.newUsersThisWeek)} new users joined this week.`);
  }
  
  return insights.length > 0 ? insights : ["No significant trends detected in the selected period."];
};

/**
 * Convert chart canvas to image
 */
export const chartToImage = async (chartElement, options = {}) => {
  try {
    const canvas = await html2canvas(chartElement, {
      backgroundColor: "#ffffff",
      scale: 3, // Higher resolution for professional output
      logging: false,
      useCORS: true,
      ...options
    });
    return canvas.toDataURL("image/png");
  } catch (error) {
    console.error("Error converting chart to image:", error);
    return null;
  }
};

/**
 * Generate Dashboard PDF Report
 */
export const generateDashboardPDF = async (stats, analytics, period, adminName) => {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let yPos = margin;
    
    const statsData = stats?.stats || stats || {};
    const periodLabel = period === "7d" ? "Last 7 Days" : period === "30d" ? "Last 30 Days" : "Last 90 Days";
    
    // Professional Header
    yPos = addReportHeader(doc, pageWidth, margin, "Dashboard Analytics Report", {
      generatedBy: adminName || "Admin",
      dateRange: periodLabel,
      filters: "All data",
      sorting: "Default"
    });
    
    // Executive Summary
    const summaryData = [
      {
        label: "Total Revenue",
        value: formatCurrency(statsData.totalRevenue || 0),
        subValue: statsData.revenueGrowth ? `Growth: ${statsData.revenueGrowth}` : null
      },
      {
        label: "Total Donations",
        value: formatCurrency(statsData.totalDonations || 0)
      },
      {
        label: "Total Orders",
        value: formatNumber(statsData.totalOrders || 0)
      },
      {
        label: "New Users",
        value: formatNumber(statsData.newUsersThisWeek || 0),
        subValue: `Total: ${formatNumber(statsData.totalUsers || 0)}`
      },
      {
        label: "Top Spender",
        value: statsData.topSpenderName || "N/A",
        subValue: statsData.topSpenderAmount ? formatCurrency(statsData.topSpenderAmount) : null
      },
      {
        label: "Most Supported Cat",
        value: analytics?.donationByCat?.[0]?.catName || "N/A",
        subValue: analytics?.donationByCat?.[0]?.totalAmount ? formatCurrency(analytics.donationByCat[0].totalAmount) : null
      }
    ];
    
    yPos = addExecutiveSummary(doc, pageWidth, pageHeight, margin, yPos, summaryData);
    
    // Analytics Insights
    const insights = generateInsights(stats, analytics, period);
    if (insights.length > 0) {
      yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Key Insights");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      doc.setFont(undefined, "normal");
      insights.forEach((insight) => {
        if (yPos > pageHeight - 25) {
          doc.addPage();
          const totalPages = doc.internal.pages.length - 1;
          addPageFooter(doc, pageWidth, pageHeight, margin, totalPages, totalPages);
          yPos = margin + 5;
        }
        doc.text(`• ${insight}`, margin + 3, yPos);
        yPos += 6;
      });
      yPos += 5;
    }
    
    // Detailed Metrics Table
    yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Detailed Metrics");
    const metricsHeaders = ["Metric", "Value"];
    const metricsRows = [
      ["Total Users", formatNumber(statsData.totalUsers || 0)],
      ["New Users (Today)", formatNumber(statsData.newUsersToday || 0)],
      ["New Users (This Week)", formatNumber(statsData.newUsersThisWeek || 0)],
      ["New Users (This Month)", formatNumber(statsData.newUsersThisMonth || 0)],
      ["Active Users", formatNumber(statsData.activeUsers || 0)],
      ["Total Revenue", formatCurrency(statsData.totalRevenue || 0)],
      ["Total Donations", formatCurrency(statsData.totalDonations || 0)],
      ["Total Orders", formatNumber(statsData.totalOrders || 0)],
      ["Pending Orders", formatNumber(statsData.pendingOrders || 0)],
      ["Top Spender", statsData.topSpenderName || "N/A"],
      ["Top Spender Amount", formatCurrency(statsData.topSpenderAmount || 0)]
    ];
    
    yPos = addTable(doc, pageWidth, pageHeight, margin, yPos, metricsHeaders, metricsRows, {
      colWidths: [100, 85],
      alignments: ["left", "right"]
    });
    
    // Charts Section
    if (analytics?.revenueOverTime?.length > 0 || analytics?.donationByCat?.length > 0) {
      yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Analytics Charts");
      
      // Revenue Over Time Chart
      if (analytics?.revenueOverTime?.length > 0) {
        try {
          await new Promise(resolve => setTimeout(resolve, 500));
          const chartContainer = document.querySelector('[data-chart="revenue"]');
          if (chartContainer && chartContainer.offsetWidth > 0) {
            const chartImage = await chartToImage(chartContainer);
            if (chartImage) {
              if (yPos + 60 > pageHeight - 25) {
                doc.addPage();
                const totalPages = doc.internal.pages.length - 1;
                addPageFooter(doc, pageWidth, pageHeight, margin, totalPages, totalPages);
                yPos = margin + 5;
              }
              
              const imgWidth = pageWidth - 2 * margin;
              const imgHeight = Math.min((chartContainer.offsetHeight * imgWidth) / chartContainer.offsetWidth, 60);
              
              doc.setFontSize(11);
              doc.setTextColor(0, 0, 0);
              doc.setFont(undefined, "bold");
              doc.text("Revenue Over Time", margin, yPos);
              yPos += 5;
              
              doc.addImage(chartImage, "PNG", margin, yPos, imgWidth, imgHeight);
              yPos += imgHeight + 5;
              
              // Chart caption
              doc.setFontSize(8);
              doc.setTextColor(100, 100, 100);
              doc.setFont(undefined, "italic");
              const revenueData = analytics.revenueOverTime;
              const firstValue = revenueData[0]?.shopRevenue || 0;
              const lastValue = revenueData[revenueData.length - 1]?.shopRevenue || 0;
              const trend = lastValue > firstValue ? "increased" : "decreased";
              doc.text(`Revenue ${trend} from ${formatCurrency(firstValue)} to ${formatCurrency(lastValue)} over the selected period.`, margin + 3, yPos);
              yPos += 8;
            }
          }
        } catch (chartError) {
          console.warn("Could not include revenue chart:", chartError);
        }
      }
      
      // Donation Distribution Chart
      if (analytics?.donationByCat?.length > 0) {
        try {
          const chartContainer = document.querySelector('[data-chart="donations"]');
          if (chartContainer && chartContainer.offsetWidth > 0) {
            const chartImage = await chartToImage(chartContainer);
            if (chartImage) {
              if (yPos + 60 > pageHeight - 25) {
                doc.addPage();
                const totalPages = doc.internal.pages.length - 1;
                addPageFooter(doc, pageWidth, pageHeight, margin, totalPages, totalPages);
                yPos = margin + 5;
              }
              
              const imgWidth = pageWidth - 2 * margin;
              const imgHeight = Math.min((chartContainer.offsetHeight * imgWidth) / chartContainer.offsetWidth, 60);
              
              doc.setFontSize(11);
              doc.setTextColor(0, 0, 0);
              doc.setFont(undefined, "bold");
              doc.text("Donation Distribution by Cat", margin, yPos);
              yPos += 5;
              
              doc.addImage(chartImage, "PNG", margin, yPos, imgWidth, imgHeight);
              yPos += imgHeight + 5;
              
              // Chart caption
              doc.setFontSize(8);
              doc.setTextColor(100, 100, 100);
              doc.setFont(undefined, "italic");
              const topCat = analytics.donationByCat[0];
              if (topCat) {
                doc.text(`${topCat.catName} received the highest donations with ${formatCurrency(topCat.totalAmount)}.`, margin + 3, yPos);
              }
              yPos += 8;
            }
          }
        } catch (chartError) {
          console.warn("Could not include donation chart:", chartError);
        }
      }
    }
    
    // Add footer to all pages
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addPageFooter(doc, pageWidth, pageHeight, margin, i, totalPages);
    }
    
    doc.save(`banana-meow-dashboard-${period}-${Date.now()}.pdf`);
  } catch (error) {
    console.error("PDF generation error:", error);
    throw error;
  }
};

/**
 * Generate Products PDF Report
 */
export const generateProductsPDF = (products, searchTerm, adminName) => {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let yPos = margin;
    
    // Professional Header
    yPos = addReportHeader(doc, pageWidth, margin, "Products Inventory Report", {
      generatedBy: adminName || "Admin",
      dateRange: "All time",
      filters: searchTerm ? `Search: "${searchTerm}"` : "None",
      sorting: "Default"
    });
    
    // Executive Summary
    const totalInventoryValue = products.reduce((sum, p) => sum + (p.price || 0) * (p.inventory || 0), 0);
    const outOfStockCount = products.filter(p => (p.inventory || 0) === 0).length;
    const bestSeller = products.reduce((best, p) => {
      const sold = (p.totalSold || 0);
      return sold > (best.totalSold || 0) ? p : best;
    }, products[0] || {});
    
    const summaryData = [
      {
        label: "Total Products",
        value: formatNumber(products.length)
      },
      {
        label: "Inventory Value",
        value: formatCurrency(totalInventoryValue)
      },
      {
        label: "Out of Stock",
        value: formatNumber(outOfStockCount)
      },
      {
        label: "Best Seller",
        value: bestSeller.name || "N/A",
        subValue: bestSeller.totalSold ? `${formatNumber(bestSeller.totalSold)} sold` : null
      }
    ];
    
    yPos = addExecutiveSummary(doc, pageWidth, pageHeight, margin, yPos, summaryData);
    
    // Products Table
    yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Product Details");
    
    const headers = ["Product Name", "Category", "Price", "Stock", "Date Created"];
    const rows = products.map((product) => [
      product.name || "N/A",
      product.category || "N/A",
      formatCurrency(product.price || 0),
      formatNumber(product.inventory || 0),
      product.createdAt ? new Date(product.createdAt).toLocaleDateString() : "N/A"
    ]);
    
    yPos = addTable(doc, pageWidth, pageHeight, margin, yPos, headers, rows, {
      colWidths: [70, 40, 30, 25, 30],
      alignments: ["left", "left", "right", "right", "left"],
      title: null
    });
    
    // Add footer to all pages
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addPageFooter(doc, pageWidth, pageHeight, margin, i, totalPages);
    }
    
    doc.save(`banana-meow-products-${Date.now()}.pdf`);
  } catch (error) {
    console.error("PDF generation error:", error);
    throw error;
  }
};

/**
 * Generate Donations PDF Report
 */
export const generateDonationsPDF = (donations, searchTerm, adminName) => {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let yPos = margin;
    
    const totalAmount = donations.reduce((sum, d) => sum + (d.amount || 0), 0);
    const avgDonation = donations.length > 0 ? totalAmount / donations.length : 0;
    const mostSupportedCat = donations.reduce((acc, d) => {
      const cat = d.cat || "Unknown";
      acc[cat] = (acc[cat] || 0) + (d.amount || 0);
      return acc;
    }, {});
    const topCat = Object.entries(mostSupportedCat).sort((a, b) => b[1] - a[1])[0];
    
    // Professional Header
    yPos = addReportHeader(doc, pageWidth, margin, "Donations Report", {
      generatedBy: adminName || "Admin",
      dateRange: "All time",
      filters: searchTerm ? `Search: "${searchTerm}"` : "None",
      sorting: "Default"
    });
    
    // Executive Summary
    const summaryData = [
      {
        label: "Total Donations",
        value: formatNumber(donations.length)
      },
      {
        label: "Total Amount",
        value: formatCurrency(totalAmount)
      },
      {
        label: "Average Donation",
        value: formatCurrency(avgDonation)
      },
      {
        label: "Most Supported Cat",
        value: topCat ? topCat[0] : "N/A",
        subValue: topCat ? formatCurrency(topCat[1]) : null
      }
    ];
    
    yPos = addExecutiveSummary(doc, pageWidth, pageHeight, margin, yPos, summaryData);
    
    // Donations Table
    yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Donation Details");
    
    const headers = ["Donor", "Cat Supported", "Amount", "Date", "Status"];
    const rows = donations.map((donation) => [
      donation.email || donation.type || "Anonymous",
      donation.cat || "N/A",
      formatCurrency(donation.amount || 0),
      donation.createdAt ? new Date(donation.createdAt).toLocaleDateString() : "N/A",
      donation.status || "pending"
    ]);
    
    // Add total row
    rows.push([
      "TOTAL",
      "",
      formatCurrency(totalAmount),
      "",
      ""
    ]);
    
    yPos = addTable(doc, pageWidth, pageHeight, margin, yPos, headers, rows, {
      colWidths: [60, 40, 35, 35, 25],
      alignments: ["left", "left", "right", "left", "left"]
    });
    
    // Add footer to all pages
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addPageFooter(doc, pageWidth, pageHeight, margin, i, totalPages);
    }
    
    doc.save(`banana-meow-donations-${Date.now()}.pdf`);
  } catch (error) {
    console.error("PDF generation error:", error);
    throw error;
  }
};

/**
 * Generate Orders PDF Report
 */
export const generateOrdersPDF = (orders, searchTerm, adminName) => {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let yPos = margin;
    
    const totalRevenue = orders.reduce((sum, o) => sum + (o.total || 0), 0);
    const completedOrders = orders.filter(o => o.status === "completed").length;
    const cancelledOrders = orders.filter(o => o.status === "cancelled").length;
    const avgOrderValue = orders.length > 0 ? totalRevenue / orders.length : 0;
    const completedPercentage = orders.length > 0 ? ((completedOrders / orders.length) * 100).toFixed(1) : 0;
    const cancelledPercentage = orders.length > 0 ? ((cancelledOrders / orders.length) * 100).toFixed(1) : 0;
    
    // Professional Header
    yPos = addReportHeader(doc, pageWidth, margin, "Orders Report", {
      generatedBy: adminName || "Admin",
      dateRange: "All time",
      filters: searchTerm ? `Search: "${searchTerm}"` : "None",
      sorting: "Default"
    });
    
    // Executive Summary
    const summaryData = [
      {
        label: "Total Orders",
        value: formatNumber(orders.length)
      },
      {
        label: "Completed",
        value: `${completedPercentage}%`,
        subValue: `${formatNumber(completedOrders)} orders`
      },
      {
        label: "Cancelled",
        value: `${cancelledPercentage}%`,
        subValue: `${formatNumber(cancelledOrders)} orders`
      },
      {
        label: "Avg Order Value",
        value: formatCurrency(avgOrderValue)
      },
      {
        label: "Total Revenue",
        value: formatCurrency(totalRevenue)
      }
    ];
    
    yPos = addExecutiveSummary(doc, pageWidth, pageHeight, margin, yPos, summaryData);
    
    // Orders Table
    yPos = addSectionDivider(doc, pageWidth, margin, yPos, "Order Details");
    
    const headers = ["Order ID", "Customer", "Products", "Total", "Status", "Date"];
    const rows = orders.map((order) => [
      `#${order._id?.slice(-8).toUpperCase() || "N/A"}`,
      order.email || "Guest",
      (order.items?.map(i => i.name).join(", ") || "N/A").substring(0, 35),
      formatCurrency(order.total || 0),
      order.status || "pending",
      order.createdAt ? new Date(order.createdAt).toLocaleDateString() : "N/A"
    ]);
    
    // Add summary row
    rows.push([
      "SUMMARY",
      "",
      `${formatNumber(orders.length)} orders`,
      formatCurrency(totalRevenue),
      "",
      ""
    ]);
    
    yPos = addTable(doc, pageWidth, pageHeight, margin, yPos, headers, rows, {
      colWidths: [30, 45, 50, 30, 25, 25],
      alignments: ["left", "left", "left", "right", "left", "left"]
    });
    
    // Add footer to all pages
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addPageFooter(doc, pageWidth, pageHeight, margin, i, totalPages);
    }
    
    doc.save(`banana-meow-orders-${Date.now()}.pdf`);
  } catch (error) {
    console.error("PDF generation error:", error);
    throw error;
  }
};
